      - name: Run Flask API with Ngrok
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_DATASET_ID: mahi1010/news_articles_daily_m
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          pip install flask pyngrok
          nohup python api/app.py &
          sleep 10
          python - <<'PY'
from pyngrok import ngrok
import time
ngrok.set_auth_token("${{ secrets.NGROK_AUTH_TOKEN }}")
tunnel = ngrok.connect(8000, "http")
print("🌐 Public URL:", tunnel.public_url)
time.sleep(3600)  # keep alive for 1 hour
PY
