name: Daily DB Refresh

on:
  schedule:
    # Runs at 00:00 UTC daily (05:30 IST)
    - cron: "0 0 * * *"
  workflow_dispatch: {}

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run refresh
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_DATASET_ID: YOURHF/news_articles_daily
          E5_NAME: intfloat/multilingual-e5-base   # multilingual embeddings
          SKIP_SUMMARY: "1"                        # start fast; we can enable summaries later
        run: |
          python refresh_db.py
